name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build


      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSh_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "., !node_modules"
          target: "~/app/api-rentx"

      - name: Update API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH._KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/app/api-rentx
            yarn
            ./node_modules/.bin/typeorm migration:run
            pm2 restart api-rentx
            
